# Generated by Django 5.1.5 on 2025-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tache_utilisateur_projet_tache_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('à faire', 'À faire'), ('en cours', 'En cours'), ('terminé', 'Terminé')], default='à faire', max_length=20),
        ),
    ]
