# Generated by Django 5.1.5 on 2025-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_projet_options_alter_tache_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé')], default='en cours', max_length=20),
        ),
    ]
